[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver2"
version_provider = "cargo"
update_changelog_on_bump = false
major_version_zero = true
changelog_merge_prerelease = true
prerelease_offset = 1
